export default [
  {
    name: "Tutoriel",
    startPosition: { width: 0, height: 5 },
    exitPosition: { width: 5, height: 5 },
    trapsPositions: [],
    boardWidth: 11,
    boardHeight: 11,
    trapShowingTime: 2,
  },
  {
    name: "Level 1",
    startPosition: { width: 0, height: 5 },
    exitPosition: { width: 10, height: 5 },
    trapsPositions: [
      { width: 2, height: 2 },
      { width: 2, height: 3 },
      { width: 2, height: 4 },
      { width: 2, height: 5 },
      { width: 2, height: 6 },
      { width: 2, height: 7 },
      { width: 2, height: 8 },
      { width: 5, height: 0 },
      { width: 5, height: 1 },
      { width: 5, height: 2 },
      { width: 5, height: 3 },
      { width: 5, height: 7 },
      { width: 5, height: 8 },
      { width: 5, height: 9 },
      { width: 5, height: 10 },
      { width: 8, height: 2 },
      { width: 8, height: 3 },
      { width: 8, height: 4 },
      { width: 8, height: 5 },
      { width: 8, height: 6 },
      { width: 8, height: 7 },
      { width: 8, height: 8 },
    ],
    boardWidth: 11,
    boardHeight: 11,
    trapShowingTime: 2,
  },
  {
    name: "Level 2",
    startPosition: { width: 0, height: 0 },
    exitPosition: { width: 10, height: 10 },
    trapsPositions: [
      { width: 0, height: 2 },
      { width: 1, height: 2 },
      { width: 2, height: 2 },
      { width: 4, height: 2 },
      { width: 5, height: 2 },
      { width: 6, height: 2 },
      { width: 7, height: 2 },
      { width: 8, height: 2 },
      { width: 9, height: 2 },
      { width: 10, height: 2 },
      { width: 0, height: 5 },
      { width: 1, height: 5 },
      { width: 2, height: 5 },
      { width: 3, height: 5 },
      { width: 4, height: 5 },
      { width: 5, height: 5 },
      { width: 6, height: 5 },
      { width: 7, height: 5 },
      { width: 8, height: 5 },
      { width: 10, height: 5 },
      { width: 0, height: 8 },
      { width: 1, height: 8 },
      { width: 2, height: 8 },
      { width: 3, height: 8 },
      { width: 4, height: 8 },
      { width: 6, height: 8 },
      { width: 7, height: 8 },
      { width: 8, height: 8 },
      { width: 9, height: 8 },
      { width: 10, height: 8 },
    ],
    boardWidth: 11,
    boardHeight: 11,
    trapShowingTime: 3,
  },
];
